name: Composite action1

inputs:
  whowho:
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: 'composite'
  steps:
    - name: Say
      run: echo "Hello $INPUT_GREET"
      shell: bash
      env:
        $INPUT_GREET: ${{ inputs.whowho }}    