name: Caching learnings

on: 
  workflow_dispatch:

jobs:
  node-js:
    name: setup node js
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: cache/node-project
    steps:
      - uses: actions/checkout@130a169078a413d3a5246a393625e8e742f387f6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
      - with:
          node-version: 20
          cache: npm
          cache-dependency-path: cache/node-project 
      - name: Install npm dependecies
        runs: npm ci --prefer=offline 
      - name: List few modules
        runs: ls -R node_modules | head  






  caching:
    name: Demo-caching
    runs-on: ubuntu-24.04
    steps:
      - name: Restore cache
        id: demo-cache
        uses: actions/cache@v5
        with:
          path: demo-cache/
          key: looking-for-internship 

      - name: Create cache
        if: steps.demo-cache.outputs.cache-hit  != 'true'
        run: |
          echo "Creating a cache"
          mkdir -p demo-cache
          date > demo-cache/time.txt

      - name: Save cache
        if: steps.demo-cache.outputs.cache-hit !='true'
        uses: actions/cache@v5
        with:
          path: demo-cache/
          key: looking-for-internship

      - name: Verify cache
        run: |
          echo "Hit status -> ${{ steps.demo-cache.outputs.cache-hit }}"    
          cat demo-cache/time.txt    
          
      
      


