name: Matrices 

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Matrix-jobs:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        number: [1,2]
        letter: [a,b,c]
        exclude:
          - number: 1
            letter: c
    timeout-minutes: 5     
  
    steps:
      - name: First step
        run: |
          echo "Number ${{ matrix.number }}" 
          echo "Letter ${{ matrix.letter }}"

      - name: Second step 
        if: ${{ !(matrix.number == 1 && matrix.letter == 'b') }}
        run: echo "condition executed for ${{ matrix.number }}${{ matrix.letter }}" 

  sleep-jobs:
    runs-on : ubuntu-24.04
    steps:
      - name: sleep
        run: sleep 100
    timeout-minutes: 5
              
   